//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dz.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingDarkMode {
            get {
                return ((bool)(this["SettingDarkMode"]));
            }
            set {
                this["SettingDarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("«")]
        public string SettingBracketOpen {
            get {
                return ((string)(this["SettingBracketOpen"]));
            }
            set {
                this["SettingBracketOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("»")]
        public string SettingBracketClose {
            get {
                return ((string)(this["SettingBracketClose"]));
            }
            set {
                this["SettingBracketClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SettingCodeLength {
            get {
                return ((int)(this["SettingCodeLength"]));
            }
            set {
                this["SettingCodeLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DZ")]
        public string SettingTitleText {
            get {
                return ((string)(this["SettingTitleText"]));
            }
            set {
                this["SettingTitleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingTitleTip {
            get {
                return ((bool)(this["SettingTitleTip"]));
            }
            set {
                this["SettingTitleTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SettingFrequency {
            get {
                return ((int)(this["SettingFrequency"]));
            }
            set {
                this["SettingFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>test</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SettingDB {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SettingDB"]));
            }
            set {
                this["SettingDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RControlKey")]
        public global::System.Windows.Forms.Keys SettingSpecialKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["SettingSpecialKey"]));
            }
            set {
                this["SettingSpecialKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingWordWrap {
            get {
                return ((bool)(this["SettingWordWrap"]));
            }
            set {
                this["SettingWordWrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double SettingOpacity {
            get {
                return ((double)(this["SettingOpacity"]));
            }
            set {
                this["SettingOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingTopMost {
            get {
                return ((bool)(this["SettingTopMost"]));
            }
            set {
                this["SettingTopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public int SettingLocationTop {
            get {
                return ((int)(this["SettingLocationTop"]));
            }
            set {
                this["SettingLocationTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78")]
        public int SettingLocationLeft {
            get {
                return ((int)(this["SettingLocationLeft"]));
            }
            set {
                this["SettingLocationLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("268")]
        public int SettingHeight {
            get {
                return ((int)(this["SettingHeight"]));
            }
            set {
                this["SettingHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int SettingWidth {
            get {
                return ((int)(this["SettingWidth"]));
            }
            set {
                this["SettingWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SettingListboxSelectedIndex {
            get {
                return ((int)(this["SettingListboxSelectedIndex"]));
            }
            set {
                this["SettingListboxSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.25")]
        public float SettingListBoxFontSize {
            get {
                return ((float)(this["SettingListBoxFontSize"]));
            }
            set {
                this["SettingListBoxFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingTabIndex {
            get {
                return ((int)(this["SettingTabIndex"]));
            }
            set {
                this["SettingTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingTextBox {
            get {
                return ((string)(this["SettingTextBox"]));
            }
            set {
                this["SettingTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingSelectionStart {
            get {
                return ((int)(this["SettingSelectionStart"]));
            }
            set {
                this["SettingSelectionStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingSelectionLength {
            get {
                return ((int)(this["SettingSelectionLength"]));
            }
            set {
                this["SettingSelectionLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float SettingTextBoxZoomFactor {
            get {
                return ((float)(this["SettingTextBoxZoomFactor"]));
            }
            set {
                this["SettingTextBoxZoomFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public int SettingSplitterDistance {
            get {
                return ((int)(this["SettingSplitterDistance"]));
            }
            set {
                this["SettingSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int SettingSplitterWidth {
            get {
                return ((int)(this["SettingSplitterWidth"]));
            }
            set {
                this["SettingSplitterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingBackgroundImage {
            get {
                return ((string)(this["SettingBackgroundImage"]));
            }
            set {
                this["SettingBackgroundImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingIcon {
            get {
                return ((string)(this["SettingIcon"]));
            }
            set {
                this["SettingIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingSendkeysOnlyMode {
            get {
                return ((bool)(this["SettingSendkeysOnlyMode"]));
            }
            set {
                this["SettingSendkeysOnlyMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("‹")]
        public string SettingIgnoreWhiteSpaceOpen {
            get {
                return ((string)(this["SettingIgnoreWhiteSpaceOpen"]));
            }
            set {
                this["SettingIgnoreWhiteSpaceOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("›")]
        public string SettingIgnoreWhiteSpaceClose {
            get {
                return ((string)(this["SettingIgnoreWhiteSpaceClose"]));
            }
            set {
                this["SettingIgnoreWhiteSpaceClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("į")]
        public string SettingInsertSymbol {
            get {
                return ((string)(this["SettingInsertSymbol"]));
            }
            set {
                this["SettingInsertSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingInfiniteLoop {
            get {
                return ((bool)(this["SettingInfiniteLoop"]));
            }
            set {
                this["SettingInfiniteLoop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingBracketModeOnlyScan {
            get {
                return ((bool)(this["SettingBracketModeOnlyScan"]));
            }
            set {
                this["SettingBracketModeOnlyScan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingFirstLoad {
            get {
                return ((int)(this["SettingFirstLoad"]));
            }
            set {
                this["SettingFirstLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color SettingDarkModeText {
            get {
                return ((global::System.Drawing.Color)(this["SettingDarkModeText"]));
            }
            set {
                this["SettingDarkModeText"] = value;
            }
        }
    }
}
